#!/bin/zsh

# Courtesy of Luke Smith.

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

case $BLOCK_BUTTON in
	3) notify-send "🔋 Battery module" "🔋: discharging
🛑: not charging
♻: stagnant charge
: charging
: charged
❗: battery very low!
- Scroll to change adjust xbacklight." ;;
	4) xbacklight -inc 10 ;;
	5) xbacklight -dec 10 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status")" in
		"Full") bstatus=" " ;;
		"Discharging") bstatus="" ;;
		"Charging") bstatus="" ;;
		"Not charging") bstatus=" " ;;
		"Unknown") bstatus="♻️" ;;
	esac
	capacity=$(echo "scale=0; 100 * $(cat $battery/energy_now) / $(cat $battery/energy_full)" | bc)

	[ $capacity -gt 100 ] && capcity = 100

	# Will make a warn variable if discharging and low
	[ "$bstatus" = "🔋" ] && [ "$capacity" -le 25 ] && warn="❗"
	# Prints the info
	printf "%s%s%d%%\n" "$bstatus" "$warn" "$capacity"; unset warn
done && exit 0
